/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface RiskOracleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "authorizeOracle"
      | "authorizedOracles"
      | "getResult"
      | "owner"
      | "results"
      | "revokeOracle"
      | "storeResult"
      | "transferOwnership"
      | "verifyProof"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OracleAuthorized"
      | "OracleRevoked"
      | "RiskResultStored"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "authorizeOracle",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedOracles",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getResult",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "results", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "revokeOracle",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "storeResult",
    values: [AddressLike, BigNumberish, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyProof",
    values: [AddressLike, BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "authorizeOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedOracles",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getResult", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "results", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "revokeOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "storeResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyProof",
    data: BytesLike
  ): Result;
}

export namespace OracleAuthorizedEvent {
  export type InputTuple = [oracle: AddressLike];
  export type OutputTuple = [oracle: string];
  export interface OutputObject {
    oracle: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OracleRevokedEvent {
  export type InputTuple = [oracle: AddressLike];
  export type OutputTuple = [oracle: string];
  export interface OutputObject {
    oracle: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RiskResultStoredEvent {
  export type InputTuple = [
    contractHash: BytesLike,
    contractAddress: AddressLike,
    score: BigNumberish,
    proof: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    contractHash: string,
    contractAddress: string,
    score: bigint,
    proof: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    contractHash: string;
    contractAddress: string;
    score: bigint;
    proof: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RiskOracle extends BaseContract {
  connect(runner?: ContractRunner | null): RiskOracle;
  waitForDeployment(): Promise<this>;

  interface: RiskOracleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  authorizeOracle: TypedContractMethod<
    [oracle: AddressLike],
    [void],
    "nonpayable"
  >;

  authorizedOracles: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  getResult: TypedContractMethod<
    [contractAddress: AddressLike, timestamp: BigNumberish],
    [
      [bigint, string, bigint, string, boolean] & {
        score: bigint;
        proofHash: string;
        resultTimestamp: bigint;
        oracleAddress: string;
        exists: boolean;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  results: TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, string, bigint, string, boolean] & {
        score: bigint;
        proof: string;
        timestamp: bigint;
        oracle: string;
        exists: boolean;
      }
    ],
    "view"
  >;

  revokeOracle: TypedContractMethod<
    [oracle: AddressLike],
    [void],
    "nonpayable"
  >;

  storeResult: TypedContractMethod<
    [
      contractAddress: AddressLike,
      score: BigNumberish,
      proofHash: BytesLike,
      timestamp: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  verifyProof: TypedContractMethod<
    [
      contractAddress: AddressLike,
      timestamp: BigNumberish,
      proofHash: BytesLike
    ],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "authorizeOracle"
  ): TypedContractMethod<[oracle: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "authorizedOracles"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "getResult"
  ): TypedContractMethod<
    [contractAddress: AddressLike, timestamp: BigNumberish],
    [
      [bigint, string, bigint, string, boolean] & {
        score: bigint;
        proofHash: string;
        resultTimestamp: bigint;
        oracleAddress: string;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "results"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, string, bigint, string, boolean] & {
        score: bigint;
        proof: string;
        timestamp: bigint;
        oracle: string;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "revokeOracle"
  ): TypedContractMethod<[oracle: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "storeResult"
  ): TypedContractMethod<
    [
      contractAddress: AddressLike,
      score: BigNumberish,
      proofHash: BytesLike,
      timestamp: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifyProof"
  ): TypedContractMethod<
    [
      contractAddress: AddressLike,
      timestamp: BigNumberish,
      proofHash: BytesLike
    ],
    [boolean],
    "view"
  >;

  getEvent(
    key: "OracleAuthorized"
  ): TypedContractEvent<
    OracleAuthorizedEvent.InputTuple,
    OracleAuthorizedEvent.OutputTuple,
    OracleAuthorizedEvent.OutputObject
  >;
  getEvent(
    key: "OracleRevoked"
  ): TypedContractEvent<
    OracleRevokedEvent.InputTuple,
    OracleRevokedEvent.OutputTuple,
    OracleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "RiskResultStored"
  ): TypedContractEvent<
    RiskResultStoredEvent.InputTuple,
    RiskResultStoredEvent.OutputTuple,
    RiskResultStoredEvent.OutputObject
  >;

  filters: {
    "OracleAuthorized(address)": TypedContractEvent<
      OracleAuthorizedEvent.InputTuple,
      OracleAuthorizedEvent.OutputTuple,
      OracleAuthorizedEvent.OutputObject
    >;
    OracleAuthorized: TypedContractEvent<
      OracleAuthorizedEvent.InputTuple,
      OracleAuthorizedEvent.OutputTuple,
      OracleAuthorizedEvent.OutputObject
    >;

    "OracleRevoked(address)": TypedContractEvent<
      OracleRevokedEvent.InputTuple,
      OracleRevokedEvent.OutputTuple,
      OracleRevokedEvent.OutputObject
    >;
    OracleRevoked: TypedContractEvent<
      OracleRevokedEvent.InputTuple,
      OracleRevokedEvent.OutputTuple,
      OracleRevokedEvent.OutputObject
    >;

    "RiskResultStored(bytes32,address,uint256,bytes32,uint256)": TypedContractEvent<
      RiskResultStoredEvent.InputTuple,
      RiskResultStoredEvent.OutputTuple,
      RiskResultStoredEvent.OutputObject
    >;
    RiskResultStored: TypedContractEvent<
      RiskResultStoredEvent.InputTuple,
      RiskResultStoredEvent.OutputTuple,
      RiskResultStoredEvent.OutputObject
    >;
  };
}
