/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ShieldedVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "balances"
      | "checkRiskScore"
      | "deposit"
      | "emergencyWithdraw"
      | "executeWithRiskCheck"
      | "maxRiskScore"
      | "owner"
      | "pause"
      | "paused"
      | "renounceOwnership"
      | "riskOracleAddress"
      | "riskOracleUrl"
      | "setMaxRiskScore"
      | "setRiskOracleUrl"
      | "transferOwnership"
      | "unpause"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Deposited"
      | "EmergencyWithdrawn"
      | "MaxRiskScoreUpdated"
      | "OwnershipTransferred"
      | "Paused"
      | "RiskOracleUrlUpdated"
      | "TransactionAllowed"
      | "TransactionBlocked"
      | "Unpaused"
      | "Withdrawn"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "balances",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "checkRiskScore",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "deposit", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executeWithRiskCheck",
    values: [AddressLike, BytesLike, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "maxRiskScore",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "riskOracleAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "riskOracleUrl",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxRiskScore",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setRiskOracleUrl",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "balances", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "checkRiskScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeWithRiskCheck",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxRiskScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "riskOracleAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "riskOracleUrl",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxRiskScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRiskOracleUrl",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace DepositedEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmergencyWithdrawnEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MaxRiskScoreUpdatedEvent {
  export type InputTuple = [oldScore: BigNumberish, newScore: BigNumberish];
  export type OutputTuple = [oldScore: bigint, newScore: bigint];
  export interface OutputObject {
    oldScore: bigint;
    newScore: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RiskOracleUrlUpdatedEvent {
  export type InputTuple = [oldUrl: string, newUrl: string];
  export type OutputTuple = [oldUrl: string, newUrl: string];
  export interface OutputObject {
    oldUrl: string;
    newUrl: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransactionAllowedEvent {
  export type InputTuple = [
    user: AddressLike,
    target: AddressLike,
    riskScore: BigNumberish
  ];
  export type OutputTuple = [user: string, target: string, riskScore: bigint];
  export interface OutputObject {
    user: string;
    target: string;
    riskScore: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransactionBlockedEvent {
  export type InputTuple = [
    user: AddressLike,
    target: AddressLike,
    riskScore: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [
    user: string,
    target: string,
    riskScore: bigint,
    reason: string
  ];
  export interface OutputObject {
    user: string;
    target: string;
    riskScore: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawnEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ShieldedVault extends BaseContract {
  connect(runner?: ContractRunner | null): ShieldedVault;
  waitForDeployment(): Promise<this>;

  interface: ShieldedVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  balances: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  checkRiskScore: TypedContractMethod<
    [riskScore: BigNumberish],
    [boolean],
    "view"
  >;

  deposit: TypedContractMethod<[], [void], "payable">;

  emergencyWithdraw: TypedContractMethod<
    [user: AddressLike],
    [void],
    "nonpayable"
  >;

  executeWithRiskCheck: TypedContractMethod<
    [
      target: AddressLike,
      callData: BytesLike,
      value: BigNumberish,
      riskScore: BigNumberish,
      proof: BytesLike
    ],
    [boolean],
    "payable"
  >;

  maxRiskScore: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  riskOracleAddress: TypedContractMethod<[], [string], "view">;

  riskOracleUrl: TypedContractMethod<[], [string], "view">;

  setMaxRiskScore: TypedContractMethod<
    [_newMaxRiskScore: BigNumberish],
    [void],
    "nonpayable"
  >;

  setRiskOracleUrl: TypedContractMethod<
    [_newRiskOracleUrl: string],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  withdraw: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "balances"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "checkRiskScore"
  ): TypedContractMethod<[riskScore: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<[user: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "executeWithRiskCheck"
  ): TypedContractMethod<
    [
      target: AddressLike,
      callData: BytesLike,
      value: BigNumberish,
      riskScore: BigNumberish,
      proof: BytesLike
    ],
    [boolean],
    "payable"
  >;
  getFunction(
    nameOrSignature: "maxRiskScore"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "riskOracleAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "riskOracleUrl"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setMaxRiskScore"
  ): TypedContractMethod<
    [_newMaxRiskScore: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setRiskOracleUrl"
  ): TypedContractMethod<[_newRiskOracleUrl: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "Deposited"
  ): TypedContractEvent<
    DepositedEvent.InputTuple,
    DepositedEvent.OutputTuple,
    DepositedEvent.OutputObject
  >;
  getEvent(
    key: "EmergencyWithdrawn"
  ): TypedContractEvent<
    EmergencyWithdrawnEvent.InputTuple,
    EmergencyWithdrawnEvent.OutputTuple,
    EmergencyWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "MaxRiskScoreUpdated"
  ): TypedContractEvent<
    MaxRiskScoreUpdatedEvent.InputTuple,
    MaxRiskScoreUpdatedEvent.OutputTuple,
    MaxRiskScoreUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "RiskOracleUrlUpdated"
  ): TypedContractEvent<
    RiskOracleUrlUpdatedEvent.InputTuple,
    RiskOracleUrlUpdatedEvent.OutputTuple,
    RiskOracleUrlUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TransactionAllowed"
  ): TypedContractEvent<
    TransactionAllowedEvent.InputTuple,
    TransactionAllowedEvent.OutputTuple,
    TransactionAllowedEvent.OutputObject
  >;
  getEvent(
    key: "TransactionBlocked"
  ): TypedContractEvent<
    TransactionBlockedEvent.InputTuple,
    TransactionBlockedEvent.OutputTuple,
    TransactionBlockedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawn"
  ): TypedContractEvent<
    WithdrawnEvent.InputTuple,
    WithdrawnEvent.OutputTuple,
    WithdrawnEvent.OutputObject
  >;

  filters: {
    "Deposited(address,uint256)": TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;
    Deposited: TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;

    "EmergencyWithdrawn(address,uint256)": TypedContractEvent<
      EmergencyWithdrawnEvent.InputTuple,
      EmergencyWithdrawnEvent.OutputTuple,
      EmergencyWithdrawnEvent.OutputObject
    >;
    EmergencyWithdrawn: TypedContractEvent<
      EmergencyWithdrawnEvent.InputTuple,
      EmergencyWithdrawnEvent.OutputTuple,
      EmergencyWithdrawnEvent.OutputObject
    >;

    "MaxRiskScoreUpdated(uint256,uint256)": TypedContractEvent<
      MaxRiskScoreUpdatedEvent.InputTuple,
      MaxRiskScoreUpdatedEvent.OutputTuple,
      MaxRiskScoreUpdatedEvent.OutputObject
    >;
    MaxRiskScoreUpdated: TypedContractEvent<
      MaxRiskScoreUpdatedEvent.InputTuple,
      MaxRiskScoreUpdatedEvent.OutputTuple,
      MaxRiskScoreUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "RiskOracleUrlUpdated(string,string)": TypedContractEvent<
      RiskOracleUrlUpdatedEvent.InputTuple,
      RiskOracleUrlUpdatedEvent.OutputTuple,
      RiskOracleUrlUpdatedEvent.OutputObject
    >;
    RiskOracleUrlUpdated: TypedContractEvent<
      RiskOracleUrlUpdatedEvent.InputTuple,
      RiskOracleUrlUpdatedEvent.OutputTuple,
      RiskOracleUrlUpdatedEvent.OutputObject
    >;

    "TransactionAllowed(address,address,uint256)": TypedContractEvent<
      TransactionAllowedEvent.InputTuple,
      TransactionAllowedEvent.OutputTuple,
      TransactionAllowedEvent.OutputObject
    >;
    TransactionAllowed: TypedContractEvent<
      TransactionAllowedEvent.InputTuple,
      TransactionAllowedEvent.OutputTuple,
      TransactionAllowedEvent.OutputObject
    >;

    "TransactionBlocked(address,address,uint256,string)": TypedContractEvent<
      TransactionBlockedEvent.InputTuple,
      TransactionBlockedEvent.OutputTuple,
      TransactionBlockedEvent.OutputObject
    >;
    TransactionBlocked: TypedContractEvent<
      TransactionBlockedEvent.InputTuple,
      TransactionBlockedEvent.OutputTuple,
      TransactionBlockedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "Withdrawn(address,uint256)": TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
    Withdrawn: TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
  };
}
