/**
 * x402 Payment Handler
 * 
 * Handles payment challenges and settlement
 */

import axios, { AxiosError } from 'axios';
import { PaymentChallenge, PaymentResult } from '../types';
import { PaymentRequiredError, NetworkError } from '../utils/errors';

export class PaymentHandler {
  constructor(private baseUrl: string) {}

  /**
   * Handle payment challenge
   * This should be called when a 402 Payment Required error is received
   */
  async handlePaymentChallenge(
    challenge: PaymentChallenge,
    walletClient?: any
  ): Promise<PaymentResult> {
    if (!walletClient) {
      throw new Error('Wallet client is required for payment settlement');
    }

    try {
      // Extract payment requirements from challenge
      const paymentReq = challenge.accepts[0];
      if (!paymentReq) {
        throw new Error('No payment requirements found in challenge');
      }

      // Create payment header (this would use the facilitator client)
      // For now, we'll use the backend endpoint
      const response = await axios.post(
        `${this.baseUrl}/api/payment/settle`,
        {
          paymentId: challenge.accepts[0].recipient, // This would be the payment ID
          paymentHeader: '', // This would be generated by facilitator
        }
      );

      return {
        paymentId: response.data.paymentId,
        txHash: response.data.txHash,
        settled: response.data.settled,
      };
    } catch (error: any) {
      if (error instanceof AxiosError && !error.response) {
        throw new NetworkError('Network error. Please check your connection.');
      }
      throw error;
    }
  }

  /**
   * Verify payment status
   */
  async verifyPayment(paymentId: string): Promise<boolean> {
    try {
      const response = await axios.get(`${this.baseUrl}/api/payment/verify`, {
        params: { paymentId },
      });

      return response.data.verified === true;
    } catch (error: any) {
      if (error instanceof AxiosError && !error.response) {
        throw new NetworkError('Network error. Please check your connection.');
      }
      throw error;
    }
  }
}
